name: Build Flet APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Bağımlılıkları Yükle
        run: |
          pip install -r requirements.txt

      - name: APK Derleme Adımı
        run: |
          flet build apk

      - name: Üretilen APK Dosyasını Çıkar
        uses: actions/upload-artifact@v4
        with:
          name: Zemin-Mekanigi-Uygulamasi
          path: build/apk/*.apk
